openapi: 3.0.0
info:
  title: My Company API
  description: API Documentation for a MyCompany.
  version: 1.0.0
servers:
  # - url: https://mycompany.com/api/v1
  #   description: Production server
  - url: http://localhost:3000/api/v1
    description: Local Development server
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken
      description: Access token stored in httpOnly cookieAuth

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: redaksi@mycompany.com
                password:
                  type: string
                  format: password
                  example: password123
              required:
                - email
                - password
      responses:
        "200":
          description: Successful login, sets httpOnly cookie for tokens
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Successfully logged in
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                        format: email
                      name:
                        type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /auth/me:
    get:
      tags:
        - Auth
      summary: Get current authenticated user
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Successfully retrieved current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                        format: email
                      name:
                        type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /auth/refresh:
    get:
      summary: Refresh access token
      tags: [Auth]
      security:
        - cookieAuth: []
      responses:
        "200":
          description: New access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Successfully create a new access token
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
  /auth/logout:
    delete:
      summary: Logout user
      tags: [Auth]
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: Successfully logout
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
        "500":
          description: Internal server error
